roles:
  web: 192.168.1.170
  
  #app: kern.local
  #there you go mf
  #db: 192.168.1.170
  
application: kern
# create this user on production server
user: deployer
# create this group on production server
group: deployer
# create this dir on production server 
sql_backup: "$HOME/sql_backup"

db_user: "deployer"

db_passwd: "deployer"

db_name: "kern"
